language: python

# Supported Python versions
dist: xenial  # required for Python >= 3.7
python:
  - 3.7
  - 3.6

# Supported PyTorch versions
env:
  - PYTORCH=1.2.0
  - PYTORCH=1.1.0
  - PYTORCH=1.0.1
  - PYTORCH=1.0.0

stages:
  - lint
  - test

# Run Lint first with Python 3.6 and PyTorch 1.0.0.
jobs:
  include:
    - stage: lint
      install:
        - pip install torch==$PYTORCH
        - pip install flake8 mypy
        - lint () { flake8 "$1" && mypy "$1"; }
      script:
        - lint .
        - lint examples/resnet
        - lint examples/resnet101_performance_benchmark
        - lint examples/resnet101_accuracy_benchmark
        - lint examples/amoebanet
        - lint examples/amoebanetd_performance_benchmark

# Test with various Python and PyTorch versions.
install:
  - pip install pytest-cov coveralls
  - pip install torch==$PYTORCH
  - python setup.py install
script:
  - PYTEST_ADDOPTS='--cov torchgpipe' python setup.py test
after_success:
  - coveralls
